### PR TITLE
adding myself to the participants list

### PR DESCRIPTION
**Pull request by donseba**
adding myself to the participants list. I'm not 100% sure i can make it. If it could be held during the day, it would be a lot easier, but I will do my best to make it there

### CODE REVIEW

**Comment by laurentvd** [comment]
😂

**Comment by donseba** [comment]
haha. lol , cleaning up old repositories

**Comment by laurentvd** [comment]
I had no idea this 'PR' was even open. I don't remember you making it to the meetup 10 years ago, did you go?

**Comment by donseba** [comment]
probably not! You never accepted me 😒🤣

**Pull request closed without merging**
